# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13G5aTmh1cJk8i9aTokfnxdEKrfzT1uMF
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np
from fastapi.middleware.cors import CORSMiddleware

model = joblib.load("fleetcare_model.joblib")
scaler = joblib.load("scaler.joblib")

app = FastAPI()

# Allow your Lovable UI to talk to this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Define the input data structure
class VehicleData(BaseModel):
    engine_rpm: float
    lub_oil_pressure: float
    fuel_pressure: float
    coolant_pressure: float
    lub_oil_temp: float
    coolant_temp: float
    # Note: For the sake of the UI, we'll calculate the
    # 'Pro' features (ratios) inside the API to keep it simple for the user.

@app.get("/")
def home():
    return {"message": "Mac's FleetCare API is Online"}

@app.post("/predict")
def predict(data: VehicleData):
    # Calculate engineered features exactly as we did in the notebook
    thermal_stress = data.lub_oil_temp - data.coolant_temp
    oil_pressure_ratio = data.lub_oil_pressure / (data.engine_rpm + 1)
    total_pressure_load = data.fuel_pressure + data.coolant_pressure

    # Create the feature vector in the EXACT order the model expects
    # (Engine rpm, Lub oil pressure, Fuel pressure, Coolant pressure,
    # lub oil temp, Coolant temp, thermal_stress, oil_pressure_ratio, total_pressure_load)
    features = np.array([[
        data.engine_rpm, data.lub_oil_pressure, data.fuel_pressure,
        data.coolant_pressure, data.lub_oil_temp, data.coolant_temp,
        thermal_stress, oil_pressure_ratio, total_pressure_load
    ]])

    # Scale the features
    scaled_features = scaler.transform(features)

    # Get Probability of "Bad" (Class 0)
    prob_bad = model.predict_proba(scaled_features)[0][0]

    # Apply our 30% Safety Threshold
    status = "Maintenance Required" if prob_bad > 0.30 else "Healthy"

    return {
        "failure_probability": round(float(prob_bad) * 100, 2),
        "status": status,
        "recommendation": "Check sensors immediately" if status == "Maintenance Required" else "Vehicle is optimal"
    }